version: '3'

services:
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mvc_sample
    ports:
      - 5432:5432
    networks:
      - postgres-network
    volumes:
      - db_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin/

networks:
  postgres-network:
    driver: bridge

volumes:
  db_data:
  pgadmin_data:
